### ISSUE TITLE
Bug not compatible with get_storage

### ISSUE THREAD

**Issue by zakblacki** [darwin-morocho/flutter-facebook-auth#111]
This packages is not compatible with `get_storage`  resulting on app crash on start  when calling   `await GetStorage.init();` with 

   ```
`Future<UserCredential> signInWithFacebook() async {
    final AccessToken result = (await FacebookAuth.instance.login()) as AccessToken;

    final FacebookAuthCredential facebookAuthCredential =
        FacebookAuthProvider.credential(result.token);

    return await FirebaseAuth.instance
        .signInWithCredential(facebookAuthCredential);
    }`
```

this was discussed in [here ](https://github.com/jonataslaw/get_storage/issues/33) but so far no fix was given, 

here is the log result below 

![image](https://user-images.githubusercontent.com/29728429/122426145-4b453880-cf90-11eb-968f-c3285457b2bf.png)

**Comment by darwin-morocho** [comment]
> here

Hi this plugin is compatible with any other package or plugin but you need to read the documentation.

IMPORTANT: When you install this plugin you need to configure the plugin on Android before run the project again . If you don't do it you will have a No implementation found error because the facebook SDK on Android throws an Exception when the configuration is not defined yet and this locks the other plugins in your project. If you don't need the plugin yet please remove or comment it.

**Comment by darwin-morocho** [comment]
> > here
> 
> Hi this plugin is compatible with any other package or plugin but you need to read the documentation.
> 
> IMPORTANT: When you install this plugin you need to configure the plugin on Android before run the project again . If you don't do it you will have a No implementation found error because the facebook SDK on Android throws an Exception when the configuration is not defined yet and this locks the other plugins in your project. If you don't need the plugin yet please remove or comment it.

For more info go to https://facebook.meedu.app/#/

Also for no null safety you need to use `flutter_facebook_auth: ^3.3.3-no-nullsafety`
