### ISSUE TITLE
For iOS Facebook dialog does not close automatically after login via FB app 

### ISSUE THREAD

**Issue by Gopalkrishanbairagi** [darwin-morocho/flutter-facebook-auth#169]
For iOS Facebook login, login dialog appears then it redirects the user to the Facebook application then after login it redirects the user back to the application where dialog is still open and closing it throws an error.

**Comment by darwin-morocho** [comment]
> I've added the bundle ID on the Facebook developer console and also added fb id, name, url scheme and application queries scheme in Info.plist file. These are mentioned in the documentation. If anything missing other than that, please let me know.
> 
> Note: If I delete the Facebook app from iPhone, then it opens webview based authentication which is working perfectly fine.

As I said before to help you you need to follow the issue template

**Describe the bug**
A clear and concise description of what the bug is.

**Environment**
Add your `flutter doctor -v`
Add your `pubspec.yaml`
Add your `Info.plist`
Add your `AppDelegate.swift`
Add your `MainActivity`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**To Reproduce**
Please add your code to reproduce the issue

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by thongvo109** [comment]
> We are also facing the exact issue as well. Basically Facebook login stop working on iOS when the Facebook app is installed on the iPhone and user is not logged in to Facebook on Safari.
> 
> 
> 
> During Facebook login, there is an additional steps to login from the app itself which basically break the redirection flow.
> 
> 
> 
> If on the phone, user is login to Facebook in Safari, then the login flow will be successful.
> 
> 
> 
> https://user-images.githubusercontent.com/14193912/137648425-29eef873-6bd9-4a57-b1d9-d092c1de5917.MP4
> 
> 
> 
>  
> 
> 
> 
> 

+1 same :(

**Comment by darwin-morocho** [comment]
As I said before I need all info mentioned in the issue template. If you have custom code in your AppDelegate.swift maybe. your are overriding the facebook callback. please clone the project and run the example folder remember change with your credentials let me know if the problem persists in the example app
