### ISSUE TITLE
not working for flutter web.....even the example ..'https://flutter-facebook-auth.web.app/#/' is not working...App not set up This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions...

### ISSUE THREAD

**Issue by ashishranjan3** [darwin-morocho/flutter-facebook-auth#214]
**Describe the bug**

**Environment**
Add your `flutter doctor -v`
Add your `pubspec.yaml`
Add your `Info.plist`
Add your `AppDelegate.swift`
Add your `MainActivity`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**To Reproduce**
Please add your code to reproduce the issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by darwin-morocho** [comment]
web example is working but just in dev (ONLY with dev accounts) mode because facebook now request a video with a lot of things to use the facebook sdk on production. In your case make sure you have the correct configuration in your facebook console and also add your index.html file and the initialization of the plugin for web https://facebook.meedu.app/docs/4.x.x/web

**Comment by darwin-morocho** [comment]
closed by inactivity
