### ISSUE TITLE
Return data type is different on iOS and Android

### ISSUE THREAD

**Issue by leduchung** [darwin-morocho/flutter-facebook-auth#383]
### What version are you using?

flutter_facebook_auth:6.0.4

### What OS and version are you using to local deploy your application?

macOS 14.0

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
flutter_facebook_auth: ^6.0.3
```

### Describe the Bug

In Flutter code, after logging user in, try to get user data by command:

```
Map<String, dynamic> responseUser = await FacebookAuth.instance.getUserData();
print(responseUser['picture'].runtimeType);
```

On iOS, I got: `_Map<Object?, Object?>`
On Android, I got: `_Map<String, dynamic>`

### Expected Behavior

The data type should be the same on iOS and Android, so the data processing is right.
Expect: `_Map<String, dynamic>`

### To Reproduce

The bug in the getUserData() function.

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.0 23A344 darwin-arm64, locale en-AT)
    • Flutter version 3.16.4 on channel stable at /Users/dhl/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (6 weeks ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
```

**Comment by lucavenir** [comment]
This issue still persists for me for *child nodes of the returned json*.
The fix on `v 6.1.1` isn't changing its behavior.

On iOS, I still receive a `_Map<Object?, Object?>`, e.g. parameter `picture` . And indeed I receive this error:
```
type '_Map<Object?, Object?>' is not a subtype of type 'Map<String, dynamic>' in type cast
```
on that parameter.

I fear that [this fix](https://github.com/darwin-morocho/flutter-facebook-auth/commit/c32b70b4b4cab1265b4d37326b0e8aac97afae0a) isn't enough because it doesn't convert any possible internal map as well.
