### ISSUE TITLE
Please support flutter v2 embedded plugin

### ISSUE THREAD

**Issue by rockingdice** [darwin-morocho/flutter-facebook-auth#56]
**Describe the bug**
After add this plugin to my project, all other v2 embedded plugins are broken.

**To Reproduce**
Please see this issue:
https://github.com/flutter/flutter/issues/75416

**Expected behavior**
Migrated v2 plugin that won't break the whole project.

**Comment by darwin-morocho** [comment]
hi @rockingdice  this plugin supports the v2 embedded plugins by default. 

When you install this plugin you need configure the plugin on Android and iOS before run the project . If you don't do it you will have a **No implementation found error** because the Facebook sdk will try to find the configuration. If you don't need the plugin yet please remove or comment it.

**Comment by rockingdice** [comment]
hi @darwin-morocho !
I did properly configure the app.
After some digging, I found a known issue about this: https://github.com/flutter/flutter/issues/66833,
So I'm closing this issue and waiting for the flutter team to fix it.
